### ISSUE TITLE
Accredit Fairphone in a modified version of the Fairphone map + 'heaven' listings?

### ISSUE THREAD

**Issue by kees-closed** [WeAreFairphone/fpangels-hp#15]
Hi,

I've forked your repo and modified your map for my Discourse forum. It's still a work in progress. I basically use the same principles of how you retrieve data from the forum, but slightly different. Instead of a raw YAML post, I retrieve data from the JSON output of the groups. The coordinates are missing there, so I created a custom Discourse plugin which includes these extra fields so that they are available when looping the groups. Information such as the name, member count, bio and many other things are then available already from a single point of administration. And if a group is empty, it's not displayed on the map. I also use a JavaScript function to transform the group name into an email address.

Well long story short, it's still in development and I'll share and demo the things I've changed once it's done. I'll probably make a brief YouTube video to explain it. But just to make sure, do you want to be accredit for your work on the modified map? I want to do that, but maybe you don't want to be associated with others in such a way. The GitHub repo is linked to your repo, and I'll update the README.md to specifically state we used your work in accordance to GPLv3.

Let me know. The map will be displayed on this forum: https://forum.tzm.community/

**Comment by StefanBrand** [comment]
We [put some thought into replacing the YAML with the groups JSON](https://forum.fairphone.com/t/playground-features-of-this-forum/28/255), but this did not go anywhere since there was no easy way to add custom fields to groups.

There has been some discussion on group support for the [Location Plugin](https://meta.discourse.org/t/locations-plugin/69742/578?u=stefan_fairphone) or more generally [Custom fields for groups](https://meta.discourse.org/t/custom-fields-for-groups/153580/5?u=stefan_fairphone). Maybe it is worthwhile for you to contribute there. Sounds like something that the Fairphone Forum could maybe adopt. cc @ff2u

As for accreditation: Be sure to clearly make a distinction between Fairphone (the company) and WeAreFairphone (the community), the latter being responsible for the map and the angels homepage. Linking back to this repository is good.
